-- MySQL Script generated by MySQL Workbench
-- Tue Dec 30 20:03:39 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema USERS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema USERS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `USERS` DEFAULT CHARACTER SET latin1 ;
USE `USERS` ;

-- -----------------------------------------------------
-- Table `USERS`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`Category` (
  `Category_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Categoryname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Category_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`User` (
  `User_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(50) NULL DEFAULT NULL,
  `Lastname` VARCHAR(50) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `Password` VARCHAR(50) NULL DEFAULT NULL,
  `Username` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`File` (
  `File_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_ID` INT(11) NOT NULL,
  `Filename` VARCHAR(45) NULL DEFAULT NULL,
  `Filedata` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`File_ID`, `User_ID`),
  INDEX `fk_File_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_File_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `USERS`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`FileCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`FileCategory` (
  `File_ID` INT(11) NOT NULL,
  `Category_ID` INT(11) NOT NULL,
  PRIMARY KEY (`File_ID`, `Category_ID`),
  INDEX `fk_FileCategory_Category1_idx` (`Category_ID` ASC),
  CONSTRAINT `fk_FileCategory_Category1`
    FOREIGN KEY (`Category_ID`)
    REFERENCES `USERS`.`Category` (`Category_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FileCategory_File1`
    FOREIGN KEY (`File_ID`)
    REFERENCES `USERS`.`File` (`File_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`Permission` (
  `Permission_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Permissionname` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Permission_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`Role` (
  `Role_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Rolename` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Role_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`RolePermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`RolePermission` (
  `Role_ID` INT(11) NOT NULL,
  `Permission_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Permission_ID`, `Role_ID`),
  INDEX `Role_ID` (`Role_ID` ASC),
  CONSTRAINT `rolepermission_ibfk_1`
    FOREIGN KEY (`Permission_ID`)
    REFERENCES `USERS`.`Permission` (`Permission_ID`)
    ON DELETE CASCADE,
  CONSTRAINT `rolepermission_ibfk_2`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `USERS`.`Role` (`Role_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `USERS`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USERS`.`UserRole` (
  `User_ID` INT(11) NOT NULL,
  `Role_ID` INT(11) NOT NULL,
  PRIMARY KEY (`User_ID`, `Role_ID`),
  INDEX `Role_ID` (`Role_ID` ASC),
  CONSTRAINT `userrole_ibfk_1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `USERS`.`User` (`User_ID`)
    ON DELETE CASCADE,
  CONSTRAINT `userrole_ibfk_2`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `USERS`.`Role` (`Role_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
